- name: Save config file
  hosts: localhost
  roles:
    - { role: s3, when: "backend|bool == true" }
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ region }}"

- name: Deploy BlockScout
  hosts: localhost
  tasks:
   - name: Use role in loop
     include_role:
       name: main_software
     loop: "{{ chains.keys() }}"  
     loop_control:
       loop_var: chain
       index_var: index
