- name: Prepare infrastructure
  hosts: localhost
  roles:
    - { role: check }
    - { role: s3, when: "backend|bool == true" }
    - { role: dynamodb, when: "backend|bool == true" }
    - { role: main_infra }
