- name: Prepare infrastructure
  hosts: localhost
  tasks:
    - block:
        - include_role:
            name: check
        - include_role:
            name: "{{ item }}"
          with_items:
            - s3
            - dynamodb
          when: backend|bool == true
        - include_role:
            name: main_infra
      always:
        - include_role:
            name: s3_config
          when: backend|bool == true and upload_config_to_s3|bool == true
        - include_role:
            name: s3_debug
          when: backend|bool == true and upload_debug_info_to_s3|bool == true
