- name: Deploy BlockScout
  hosts: all
  tasks:
   - block:
       - name: Deploy
         include_role:
           name: main_software
         tags:
           - update_vars
           - build
           - deploy
     always:
       - include_role:
           name: s3 
         when: backend|bool and (upload_debug_info_to_s3|bool or upload_config_to_s3|bool)
       - include_role:
           name: s3_config
         when: backend|bool and upload_config_to_s3|bool 
       - include_role:
           name: s3_debug
         when: backend|bool and upload_debug_info_to_s3|bool 
