- name: Deploy BlockScout
  hosts: all
  tasks:
   - block:
       - name: Deploy
         include_role:
           name: main_software
     always:
       - include_role:
           name: s3 
         when: backend|bool == true and (upload_debug_info_to_s3|bool == true or upload_config_to_s3|bool ==true)
       - include_role:
           name: s3_config
         when: backend|bool == true and upload_config_to_s3|bool == true
       - include_role:
           name: s3_debug
         when: backend|bool == true and upload_debug_info_to_s3|bool == true
