- name: Save config file
  hosts: localhost
  roles:
    - { role: s3, when: "backend|bool == true" }

- name: Deploy BlockScout
  hosts: localhost
  tasks:
   - name: Use role in loop
     include_role:
       name: main_software
     loop: "{{ chain_custom_environment.keys() }}"  
     loop_control:
       loop_var: chain
       index_var: index
