- name: Destroy infrastructure
  hosts: localhost
  roles:
    - { role: destroy, when: "confirmation|bool == True" } 
  vars_prompt:
    - name: "confirmation"
      prompt: "Are you sure you want to destroy all the infra?"
      default: False
