- name: Create S3 bucket
  aws_s3:
    bucket: "{{ group_names[0] }}-{{ bucket }}" 
    mode: create
    permission: private
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"

- name: Apply tags and versioning to create S3 bucket
  s3_bucket:
    name: "{{ group_names[0] }}-{{ bucket }}"
    versioning: yes
    tags:
      origin: terraform
      prefix: "{{ inventory_hostname }}"
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"

- name: Add lifecycle management policy to created S3 bucket
  s3_lifecycle:
    name: "{{ group_names[0] }}-{{ bucket }}"
    rule_id: "expire"
    noncurrent_version_expiration_days: 90
    status: enabled
    state: present
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"
