- name: Create DynamoDB table
  dynamodb_table:
    name: "{{ prefix }}-{{ dynamodb_table }}"
    hash_key_name: LockID
    hash_key_type: STRING
    read_capacity: 1 
    write_capacity: 1
    tags:
      origin: terraform
      prefix: "{{ prefix }}"
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"
