- name: Create DynamoDB table
  dynamodb_table:
    name: "{{ prefix }}-{{ dynamodb_table }}"
    hash_key_name: LockID
    hash_key_type: STRING
    read_capacity: 1 
    write_capacity: 1
    tags:
      origin: terraform
      prefix: "{{ prefix }}"
