- dynamodb_table:
    name: "{{ prefix }}-{{ table }}"
    region: us-east-1
    hash_key_name: LockID
    hash_key_type: STRING
    read_capacity: 1 
    write_capacity: 1
    tags:
      origin: terraform
      prefix: "{{ prefix }}"
