- name: "Loop over config files"
  include: config.yml file={{item}}
  with_items:
    - "group_vars/all.yml"
    - "group_vars/{{ group_names[0] }}"
    - "group_vars/{{ group_names[0] }}.yml"
    - "host_vars/{{ inventory_hostname }}.yml"
    - "host_vars/{{ inventory_hostname }}"