- name: Prepare variables for Parameter Store
  set_fact:
    chain_ps_env: "{{ chain_ps_env | combine ({item.key|lower : item.value})  }}"
  with_dict: "{{ hostvars[inventory_hostname]['env_vars'] }}"
  vars:
    chain_ps_env: {}

- name: Insert variables in PS
  aws_ssm_parameter_store:
    name: "/{{ group_names[0] }}/{{ chain }}/{{ item.key }}"
    value: "{{ item.value }}"
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  with_dict: "{{ chain_ps_env }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"
