- name: Check log file exists
  stat:
    path: "{{ playbook_dir }}/log.txt"
  register: stat_result

- name: Upload logs to s3
  aws_s3:
    bucket: "{{ group_names[0] }}-{{ bucket }}"
    object: log.txt
    src: "{{ playbook_dir }}/log.txt"
    mode: put
    profile: "{{ profile }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ region }}"
  vars:
    access_key: "{{ aws_access_key|default(omit) }}"
    secret_key: "{{ aws_secret_key|default(omit) }}"
    profile: "{{ aws_profile|default(omit) }}"
    region: "{{ aws_region|default(omit) }}"
  when: stat_result.stat.exists == true